### ISSUE TITLE
Nicer ergonomics for animating materials 

### ISSUE THREAD

**Issue by LennyPenny** [mintlu8/bevy_defer#4]
Hey, thanks for this awesome crate! 

I've been animating some materials with this, however it's rather cumbersome because of having to turn the `Handle<Material>>` into the actual material by using the `Assets<Material>` resource. 

I've tried to implement an AsyncMaterialHandle by following the dance example to make this more ergonomic, but it's not working out: 

```rust

#[derive(Component)]
pub struct MyColorMaterial(Handle<ColorMaterial>);

impl AsyncComponentDeref for MyColorMaterial {
    type Target = AsyncColorMaterial;

    fn async_deref(this: &AsyncComponent<Self>) -> &Self::Target {
        AsyncColorMaterial::ref_cast(this)
    }
}

#[derive(RefCast)]
#[repr(transparent)]
pub struct AsyncColorMaterial(AsyncComponent<MyColorMaterial>);

impl AsyncColorMaterial {
    pub async fn animate(
        &self,
        target_col: Color,
        curve: impl FnMut(f32) -> f32 + Send + 'static,
        duration: impl bevy_defer::tween::AsSeconds,
    ) -> Result<(), AccessError> {
        Ok(())
    }
}
```

When I do smth like this in an async task:
```rust
let mat_handle = world.entity(entity).component::<Handle<ColorMaterial>>();
mat_handle.animate(...);
```

The animate method sadly does not show up. 

Do you have any examples of ergonomically animating a Materials properties? I'm probably missing something fundamental here..

**Comment by mintlu8** [comment]
You would need to implement on `Handle<ColorMaterial>` which is not possible currently. 
`AsyncComponentHandle` in the 0.14 branch will be a fix to this when bevy releases 0.14.

**Comment by mintlu8** [comment]
`AsyncComponentHandle` in 0.14 branch will help when animation materials once 0.14 releases.

**Comment by mintlu8** [comment]
Closed as `AsyncComponentHandle` is implemented.
